name: parcels
channels:
  - conda-forge
dependencies:
  - python>=3.8

  # Formatting
  - black
  - isort

  # Linting
  - flake8>=2.1.0
  - pre_commit
  - pydocstyle

  # Docs
  - ipython
  - numpydoc
  - nbsphinx
  - sphinx<6
  - pandoc>1.12.1,<3
  - pydata-sphinx-theme
  - sphinx-autobuild
  - myst-parser
