name: integration-tests
on:
  push:
    branches:
      - "master"
      - "test-me/*"
  pull_request:
    branches:
      - "*"
jobs:
  integration-test:
    if: github.event.pull_request.draft == false
    name: Integration testing on ${{ matrix.os }} with python latest
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: [macos, ubuntu, windows]
        include:
          - os: macOS
            os-short: osx
          - os: ubuntu
            os-short: linux
          - os: windows
            os-short: win
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          miniconda-version: "latest"
          activate-environment: py3_parcels
          environment-file: environment_py3_${{ matrix.os-short }}.yml
          auto-activate-base: false
          auto-update-conda: true
      - run: conda info
      - name: Install parcels
        run: python setup.py install
      - name: Integration test
        run: |
          parcels_get_examples examples
          pytest -v -s --nbval-lax -k "not documentation" examples
