name: linting
on:
  pull_request:
  push:
jobs:
  linting:
    name: Linting with flake8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - run: pip install flake8
      - name: flake8
        run: |
          python -m flake8 parcels
          python -m flake8 tests